### ISSUE TITLE
not getting CPU metrics ecs_cpu_seconds_total

### ISSUE THREAD

**Issue by pranaysahare** [prometheus-community/ecs_exporter#74]
I am using image URL “quay.io/prometheuscommunity/ecs-exporter:latest” , for ecs-exporter container. when I checked it exposing all the metrics or not, I saw it was not showing the CPU metrics.
 
got the same issue with the main and v0.2.1 images.
<img width="882" alt="cpu_metric_issue" src="https://github.com/prometheus-community/ecs_exporter/assets/98776939/0b7e5441-9508-42f8-9090-02276734e092">

**Comment by isker** [comment]
Seems to be missing only when running on EC2. Fargate is fine.

It must be the case that the task stats API endpoint does not return per CPU usage when running on EC2, and that's what we're relying on:
https://github.com/prometheus-community/ecs_exporter/blob/8c4f85e0c8fc656f41fe315b5e2ffbf4d92ab51d/ecscollector/collector.go#L218-L226

If that's really the case, the exporter should either degrade to the total CPU usage metrics on EC2, or it should only use those in both EC2 and Fargate. I say that because I'm not sure what the use is of getting per-CPU numbers in general here. cAdvisor agrees: https://github.com/google/cadvisor/commit/ec6da3acae09e3d2697aedbf3e2a11620dd403c6.

**Comment by isker** [comment]
Looks like this might have worked on EC2 in the past but stopped when cgroups v2 support was added here: https://github.com/aws/amazon-ecs-agent/pull/3161.

> Cgroups v2 no longer can provide per-cpu usage stats, so this validation was removed since we never used it either.
